### ISSUE TITLE
Not work for old projects

### ISSUE THREAD

**Issue by shinewanna** [miDeb/deleteable_tile#1]
I know, your initial release is not far away from now, but i want to use in my old project which have

dart: 2.10.0
flutter: 1.22.0

can u help?

**Comment by miDeb** [comment]
Thank you for your interest in this package. I primarily created it to make it easier for me to share code across projects.
You can take a look into https://github.com/miDeb/deleteable_tile/blob/main/lib/deleteable_tile.dart: It is the only file of source code and not complex. You should be able to more or less copy-and-paste the parts you are interested in and adapt them to the version of flutter/dart you need.

That said, I don't plan to release a version of this package to support older versions of flutter. I am sorry if this causes problems for you.
